### ISSUE TITLE
Don't work in fragment

### ISSUE THREAD

**Issue by bestak** [kosalgeek/generic_asynctask#1]
Hello, I have a small question, I tried this code in fragment but it gives me this error:
`java.lang.ClassCastException: com.test.fragment1 cannot be cast to android.content.Context`

Here is code which I used:

```
HashMap postData = new HashMap();
        postData.put("id", "1");

        PostResponseAsyncTask loginTask =
                new PostResponseAsyncTask(fragment1.this,postData);
        loginTask.execute("http://www.test.cz/removeUser.php");
```

What should I do?

**Comment by kosalgeek** [comment]
public class NewsFragment extends Fragment {
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        Context context = container.getContext();
        HashMap postData = new HashMap();
        postData.put("id", "1");
        PostResponseAsyncTask loginTask =
                new PostResponseAsyncTask(context, postData, new AsyncResponse(){
                      @Override
                      public void processFinish(String output) {
                            //you can get 'output' from here
                     }
                }
           );
        loginTask.execute("http://www.i-best.cz/removeUser.php");
}

try this code.

**Comment by bestak** [comment]
@kosalgeek Thanks it worked :) Can you please change url? I place here my private url by mistake ;)

**Comment by Asad2454** [comment]
Cant retrive data. Can you help me please. Empty result. But it is show no errors

Context context = container.getContext();
            HashMap postData = new HashMap();
            postData.put("mobile", "android");
            postData.put("id", SaveSharedPreference.getId(this.getActivity()));
            Log.d("imad","Chal raha ha 1");
            PostResponseAsyncTask task = new PostResponseAsyncTask(context, postData, new AsyncResponse(){

                @Override
                public void processFinish(String result) {

                    Log.d("imad","Chal raha ha 3");
                    Log.d("imad", result + " wow");
                }
            }
            );
            task.execute("http://elandmania.com/agents/Android/get_customer1");
